INSERT INTO `fase` VALUES 
-- (1,'ANALISIS','01',NULL,NULL),
-- (2,'PLANEACIÓN','02',NULL,NULL),
-- (3,'EJECUCIÓN','03',NULL,NULL),
-- (4,'EVALUACIÓN','04',NULL,NULL);
(1,'ANALISIS',NULL,NULL),
(2,'PLANEACIÓN',NULL,NULL),
(3,'EJECUCIÓN',NULL,NULL),
(4,'EVALUACIÓN',NULL,NULL);
