INSERT INTO `tipoPrograma` (`nombreTipoPrograma`) VALUES
('TECNOLOGO'),
('PROFUNDIZACIÓN TECNICA'),
('ESPECIALIZACIÓN TG'),
('TÉCNICO'),
('AUXILIAR'),
('OPERARIO'),
('FORMACIÓN COMPLEMENTARIA'),
('EDT');